spring:
  application:
    name: book-service

  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/book_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server Configuration
server:
  port: 8082

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

# Logging Configuration
logging:
  level:
    tn.esprit.book: DEBUG
    org.springframework.web: DEBUG
