
services:
  book-db:
    image: postgres:15-alpine
    container_name: book-postgres
    restart: always
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - book_db_data:/var/lib/postgresql/data

  service-book:
    build: ../Book
    container_name: book-service
    ports:
      - "8082:8082"
    depends_on:
      - book-db

volumes:
  book_db_data: